# Generated by Django 5.1.3 on 2024-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='share_data',
        ),
        migrations.AddField(
            model_name='profile',
            name='catalog_view',
            field=models.CharField(default='grid', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='color_scheme',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_family',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='profile',
            name='kerning',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='line_spacing',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_images',
            field=models.BooleanField(default=True),
        ),
    ]
