# Generated by Django 5.1.3 on 2024-12-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_profile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='catalog_view',
            field=models.CharField(choices=[('grid', 'Сетка'), ('list', 'Лист')], default='grid', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=10),
        ),
    ]
