# Generated by Django 5.1.3 on 2024-12-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_profile_enable_crazy_settings_alter_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='color_scheme',
        ),
    ]
