# Generated by Django 5.1.3 on 2024-12-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_remove_profile_color_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kerning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('system', 'Системная'), ('light', 'Светлая'), ('dark', 'Тёмная')], default='system', max_length=10),
        ),
    ]
